project:
  type: website
  output-dir: docs/
  preview:
    port: 4200
    browser: true
    navigate: true
  render:
    - "*.qmd"
    - "!vignettes/"
    - "!*.Rmd"

execute:
  freeze: auto

website:
  title: "Aqui iría el nombre de su tesis"
  # site-url: https://crumplab.com/things
  description: Tesis doctoral
  # open-graph:
  #   image: imgs/things.jpg
  # twitter-card:
  #   image: imgs/things.jpg
  # google-analytics: "G-5FFRFL1GSE"
  sidebar:
    style: "floating"
    search: true
    contents:
      - href: index.qmd
      # - href: about.qmd
        text: Inicio
      - section: "Bivariadas"
        contents:
          - section: "Centro"
            contents:
              - section: "CO y O3"
                contents:
                  - text: "FrechetFrechet"
                    href: wip.qmd
                  - text: "WeibullFrechet"
                  - text: "WeibullWeibull"
          - section: "Noreste"
          - section: "Noroeste"
          - section: "Sureste"
          - section: "Suroeste"
      - section: Marginales
        contents:
          - section: "Centro"
            contents:
              - section: "CO"
                contents:
                  - text: "Frechet"
                  - text: "Weibull"
      # - href: playground.qmd
        # text: playground
      # - href: wip.qmd
        # text: work in progress
      # - href: about.qmd
        # text: about
  page-footer: |
    Copyright 2024 Juan Antonio Vazquez.

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
    grid:
      sidebar-width: 155px
      body-width: 2000px
      margin-width: 150px

